# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"prepare_train_features": "01_question-answering.ipynb",
         "prepare_validation_features": "01_question-answering.ipynb",
         "squad_metrics": "01_question-answering.ipynb",
         "metric": "01_question-answering.ipynb",
         "QuestionAnsweringTrainingArguments": "01_question-answering.ipynb",
         "QuestionAnsweringTrainer": "01_question-answering.ipynb",
         "DistillationTrainingArguments": "02_distillation.ipynb",
         "DistillationTrainer": "02_distillation.ipynb"}

modules = ["question_answering.py",
           "distillation.py"]

doc_url = "https://lewtun.github.io/transformerlab/"

git_url = "https://github.com/lewtun/transformerlab/tree/master/"

def custom_doc_links(name): return None
